### ISSUE TITLE
Kanban Board - MediMate Appointment Booking App

### ISSUE THREAD

**Issue by mailsg** [mailsg/medimate-backend#11]
Hi,

Below are the team members of the MediMate Appointment Booking App : 
- **Charles Andrews** @forLoop94 
- **Emmanuel Tofa** @uno36 
- **Sandeep Ghosh** @mailsg 

Link to the project kanban board - https://github.com/users/mailsg/projects/7
Link to the back end repo - https://github.com/mailsg/medimate-backend
Link to the front end repo - https://github.com/mailsg/medimate-frontend

![Merged_document](https://github.com/mailsg/medimate-backend/assets/105475440/533bacc1-6805-4b99-8685-229e0f3c97ab)

Kindly review the kanban board and provide feedback.

Thanks.

**Comment by Meltrust** [comment]
Hi @mailsg,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- The pointings are fair according to the spec.✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
